### ISSUE TITLE
Missing critical information in README.md for contributors

### ISSUE THREAD

**Issue by cpoppema** [VoIPGRID/click-to-dial#25]
### Version

master

### File / Feature

README.md

### Expected behaviour

Clear instructions to be included in the README.md for working with the gulp file, explaining build targets, node/npm requirements, installation steps, production ready flags etc.

### Actual behaviour

\-

### Stacktrace / Error message

\-

### Other info

\-

**Comment by jvanveen** [comment]
Won't fix. Installation instructions are kept in the jsdocs, which the readme refers to(https://voipgrid.github.io/click-to-dial/tutorial-install.html).
