### ISSUE TITLE
OpenSans font is missing from build/

### ISSUE THREAD

**Issue by cpoppema** [VoIPGRID/click-to-dial#26]
### Version

master

### File / Feature

\-

### Expected behaviour

OpenSans font files to be present in the build target directory

### Actual behaviour

OpenSans font files are nowhere to be found

### Stacktrace / Error message

```
Failed to load resource: net::ERR_FILE_NOT_FOUND chrome-extension://fogpekdafpcofdellklpnfbnbloiflge/fonts/OpenSans-Regular.woff2
Failed to load resource: net::ERR_FILE_NOT_FOUND chrome-extension://fogpekdafpcofdellklpnfbnbloiflge/fonts/OpenSans-Italic.woff2
Failed to load resource: net::ERR_FILE_NOT_FOUND chrome-extension://fogpekdafpcofdellklpnfbnbloiflge/fonts/OpenSans-Semibold.woff2
```

### Other info

\-

**Comment by TomOffringa** [comment]
Both the Chrome and Firefox build directories have a fonts dir with the above mentioned missing fonts. 

![image](https://user-images.githubusercontent.com/5469271/28777063-dc96d98c-75f9-11e7-98e0-6aad7a7eba76.png)

**Comment by jvanveen** [comment]
Change: `const NODE_PATH = process.env.NODE_PATH || path.join(__dirname, 'node_modules') `
to : NODE_PATH = `path.join(__dirname, 'node_modules')`

**Comment by cpoppema** [comment]
That is exactly it. On the machine where this doesn't work, NODE_PATH is not empty. If I make the suggested change, it works on this machine as well!
