### ISSUE TITLE
Missing (re)connect icon

### ISSUE THREAD

**Issue by cpoppema** [VoIPGRID/click-to-dial#29]
### Version

master

### File / Feature

The blinking (re)connecting icon is just a weird spinning circle with a gap.

### Expected behaviour

This icon should be used:

![2017-07-05-1499282960_screenshot](https://user-images.githubusercontent.com/1432901/27881480-0cbf3cc0-61c9-11e7-8eca-408db00a4f6f.png)

### Actual behaviour

I see this icon:

![2017-07-05-1499282586_screenshot](https://user-images.githubusercontent.com/1432901/27881473-06cbe3ea-61c9-11e7-8d5c-50838bad3df1.png)

### Stacktrace / Error message

\-

### Other info

\-

**Comment by TomOffringa** [comment]
Tbh, I think the 'spinner' is a way more self-explanatory loading icon than a broken paperclip.

**Comment by cpoppema** [comment]
This icon isn't (just) a busy indicator; it is (also) displayed when there is no websocket connection (yet). Hence the broken link icon.

**Comment by TomOffringa** [comment]
The paperclip icon does show when there's a wrong/missing websocket connection.

![image](https://user-images.githubusercontent.com/5469271/28863122-fe1b4ede-7767-11e7-8836-86e97fb3abcb.png)
