### ISSUE TITLE
No icons in the page with firefox

### ISSUE THREAD

**Issue by cpoppema** [VoIPGRID/click-to-dial#33]
### Version

master

### File / Feature

Click-to-dial icons for detected phone numbers in websites

### Expected behaviour

Click-to-dial icons should be injected in websites

### Actual behaviour

No click-to-dial icons appear in websites

### Stacktrace / Error message

\-

Loaded xpi and tested it, so no console output.

### Other info

Firefox only, tested in v52/v53

**Comment by jvanveen** [comment]
Fixed with https://github.com/VoIPGRID/click-to-dial/commit/3727a3dde0f14826cc8c9c1c041d6fc2d9c5549c
