### ISSUE TITLE
No call status dialog for firefox

### ISSUE THREAD

**Issue by cpoppema** [VoIPGRID/click-to-dial#34]
### Version

master

### File / Feature

Call status dialog

### Expected behaviour

A call status dialog should appear after starting a call.

### Actual behaviour

Nothing happens when starting a call with the context menu (cannot use the icons, see #33)

### Stacktrace / Error message

\-

Loaded xpi and tested it, so no console output.

### Other info

Firefox only, tested in v52/v53

**Comment by TomOffringa** [comment]
Seems to work now that #33 is fixed. 

![image](https://user-images.githubusercontent.com/5469271/28825703-aa407140-76c7-11e7-8823-6ac7675035fd.png)
