### ISSUE TITLE
Clicking Settings while logged in redirects to the login page instead of showing Settings

### ISSUE THREAD

**Issue by tevas8** [VoIPGRID/click-to-dial#35]
### Version
2.0.12
For both FF and Chrome browsers.

### Description
Whenever a user that is already logged in to the plugin tries to access the Settings menu by clicking on the wheel icon, he gets redirected to the login website instead of the actual Settings website.
He then needs to enter his credentials to log in and then gets to see the Settings, but he should not need to do that since he is successfully logged in already through the plugin.

### Current behaviour
When pressing the Settings icon in the plugin, the user gets redirected to the portal´s login menu as if he was not logged in.

### Expected behaviour
When pressing the Settings icon in the plugin, the user should be redirected to the Settings page.

### Steps to reproduce
1. Log in to the Plugin
2. Click on the wheel icon to access Settings
3. Notice you are sent to the login website

**Comment by cpoppema** [comment]
This goes wrong when testing on acceptatie.voipgrid.nl, works fine on partner.voipgrid.nl, so it seems to me that the platformUrl setting from the options isn't used and attempt is made on the wrong domain to get an auto login token.

**Comment by TomOffringa** [comment]
No current issue concerning the refactor.
