### ISSUE TITLE
Radio buttons missing for the Availability menu (FF only)

### ISSUE THREAD

**Issue by tevas8** [VoIPGRID/click-to-dial#36]
### Version
2.0.12

### Description
There are no radio buttons to select whether a user is Available or not.
The functionality is okay, since the user can still change the status by pressing on the actual YES or NO messages, but it is not clear enough that YES and NO are elements the user can press to change his/her state.
While there are other visual clues for the user to figure out whether he is Available or not, the lack of the radio buttons makes it unclear enough for this to be addressed. 

### Feature containing the issue
Availability dropdown menu
 
### Current behaviour
The radio buttons the user should be able to select in order to switch from Available to Not Available are missing for the Firefox browser.

### Expected behaviour
There should be two radio buttons the user can click to change from one to the other state (Available/Not Available)

### Steps to reproduce
1. Log in to the Plugin using Firefox
2. Click on the Availability drop down menu
3. Notice the lack of radio buttons by the options YES/NO

![missing radio buttons](https://user-images.githubusercontent.com/29778372/27913511-a9e7421c-6260-11e7-9dc5-ed98e401389e.jpg)

**Comment by cpoppema** [comment]
See #37 for general styling issues. Reverting the mentioned commit there also fixes this specific issue.
