### ISSUE TITLE
Colleagues list not available when using Firefox 

### ISSUE THREAD

**Issue by tevas8** [VoIPGRID/click-to-dial#44]
### Version

click-to-dial-2.0.12 August 2017

### Browser Version
Mozilla Nightly 57.0a1 (2017-08-14) (64-bit)
Mozilla Firefox 55.0.1 (64-bit)

### Description

Whenever a user logs into the plugin it is impossible to access the Colleagues list. Clicking on the drop down menu for Colleagues does nothing.  Please refer to the screenshot for further information.

### File / Feature
Contact List

### Expected behaviour

When clicking on Colleagues the colleagues list should appear.

### Actual behaviour

When clicking on Colleagues nothing happens.

### Stacktrace / Error message

TypeError: parentDocShell.getDocShellEnumerator is not a function

### Steps to reproduce

1. Log in to the plugin
2. Wait for the "refresh wheel" to stop (you can also click right away)
3. Notice how the drop down menu does not appear showing the list of Colleagues

<img width="960" alt="unable to display colleagues list" src="https://user-images.githubusercontent.com/29778372/29317014-6f76b4e4-81ca-11e7-9653-2cb6a9afab79.png">

**Comment by TomOffringa** [comment]
Hmm. I can't reproduce this. Will test some more.

**Comment by jvanveen** [comment]
This had to do with the sendMessage callback being part of the data payload, which should have been last parameter only.
