### ISSUE TITLE
Unable to use chrome for testing (not chromium)

### ISSUE THREAD

**Issue by cpoppema** [VoIPGRID/click-to-dial#45]
### Version

master

### File / Feature

`npm run test_chromium`

### Expected behaviour

I expect the plugin to build and then start chrome instead of chromium.

### Actual behaviour

After building the plugin the script stops.

### Stacktrace / Error message

```
sh: 1: chromium: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! click-to-dial@2.0.12 test_chromium: `gulp build --target chrome;chromium --user-data-dir=/tmp/click-to-dial --load-extension=./build/chrome --no-first-run`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the click-to-dial@2.0.12 test_chromium script.
```

### Other info

There is a package called `chrome-launcher` to e.g. detect various chrome/chromium installations in PATH. It also supports [chromium on linux](https://github.com/GoogleChrome/lighthouse/commit/1c11021a41334779eed4e80d0d412266ecc1446c).

**Comment by jvanveen** [comment]
chrome-launcher uses an api. This is out-of-scope. It's expected that a developer has either the chrome or chromium executable available (or make a symlink in case the executable is called differently, like `google-chrome-beta` on my machine). I added a test_chrome command though.
