### ISSUE TITLE
Colleagues presence info is not available immediately after re-opening popup after succesful connection

### ISSUE THREAD

**Issue by cpoppema** [VoIPGRID/click-to-dial#47]
### Version

master

### File / Feature

Colleagues' presence info

### Expected behaviour

Presence info should be at the ready after re-opening the popup.

### Actual behaviour

When re-opening the popup, it looks like a new connection is made every time.

### Stacktrace / Error message

\-

### Other info

The existing plugin keeps the state in background.js and pulls it from there using request/response events

**Comment by cpoppema** [comment]
My plugin might have been in a weird state, I myself cannot reproduce this consistently. I do remember on logout that I had two error messages in background.js stating it could not disconnect because the websocket connection was already closed.

**Comment by jvanveen** [comment]
I could not reproduce this. Cleaned up connection handling though.
