### ISSUE TITLE
Error on logout

### ISSUE THREAD

**Issue by cpoppema** [VoIPGRID/click-to-dial#48]
### Version

master

### File / Feature

\-

### Expected behaviour

No errors

### Actual behaviour

Errors happen

### Stacktrace / Error message

![2017-08-22-1503385536_screenshot](https://user-images.githubusercontent.com/1432901/29553618-3672f19c-871c-11e7-90cb-86e6ac053780.png)

### Other info

\-

**Comment by TomOffringa** [comment]
@cpoppema Did you do anything specific when this error occured? Can't reproduce.

**Comment by jvanveen** [comment]
This probably happens when a timed function is executed after logging out

**Comment by cpoppema** [comment]
Not that I can remember, I tried to reproduce it but instead got this error, so maybe that one never was reached:

![2017-09-05-1504601287_screenshot](https://user-images.githubusercontent.com/1432901/30057978-486b94ee-9239-11e7-999c-43feaf1fb8dc.png)
