### ISSUE TITLE
Design of colleagues and queue list are missing cycling background colors

### ISSUE THREAD

**Issue by cpoppema** [VoIPGRID/click-to-dial#49]
### Version

master

### File / Feature

List of colleagues and list of queues

### Expected behaviour

![2017-08-22-1503387433_screenshot](https://user-images.githubusercontent.com/1432901/29554012-e4190ff6-871d-11e7-93b6-156b369ca77d.png)

### Actual behaviour

![2017-08-22-1503387441_screenshot](https://user-images.githubusercontent.com/1432901/29554017-e6d7e230-871d-11e7-9f95-2de87ba5b808.png)

### Stacktrace / Error message

\-

### Other info

\-

**Comment by TomOffringa** [comment]
https://github.com/VoIPGRID/click-to-dial/commit/de75ae55b2a7d75ce15e21c83d9b0056c562e12a
