### ISSUE TITLE
Block calling another while session is active

### ISSUE THREAD

**Issue by jvanveen** [VoIPGRID/click-to-dial#62]
### Version
2.0.13

### Expected behaviour
> If you doubleclick (or tripple click) a phonenumber the popups start overlapping. I would disable a second click/popup/callstart action as long as the popup is open.

### Actual behaviour
> The popup will even block the entire session and you won't be able to click it away (via X of click beside screen) when you open 5 popups for example.

**Comment by cpoppema** [comment]
FYI; the click event handler works fine, ie. you'll see log output when you click to close dialogs other than the last one, but nothing happens otherwise.
