### ISSUE TITLE
Queue size timer doesn't stop

### ISSUE THREAD

**Issue by cpoppema** [VoIPGRID/click-to-dial#69]
### Version

2.0.13

### File / Feature
Queue size timer

### Expected behaviour

After deselecting a selected queue, the timer should reset to 0 and stop making api calls.

### Actual behaviour

It keeps making api calls every 20 seconds.

### Stacktrace / Error message

From background.js:

(the timestamp of 47:50 was a bit late so ignore that one)

![2017-09-13-1505288912_screenshot](https://user-images.githubusercontent.com/1432901/30365714-dd422f26-9868-11e7-95e8-400e962f7f04.png)

**Comment by jvanveen** [comment]
I can't reproduce this on

**Comment by cpoppema** [comment]
I can't because there is an error before I can even try.

![2017-09-28-1506579396_screenshot](https://user-images.githubusercontent.com/1432901/30951869-7947508c-a425-11e7-8388-1e302c586250.png)
