### ISSUE TITLE
Refreshing queues doesn't work

### ISSUE THREAD

**Issue by cpoppema** [VoIPGRID/click-to-dial#70]
### Version

2.0.13

### File / Feature

Refreshing makes api calls to update every widget.

### Expected behaviour

Every widget should receive new data.

### Actual behaviour

The queue widget seems to refresh indefinitely

### Stacktrace / Error message

![2017-09-13-1505289464_screenshot](https://user-images.githubusercontent.com/1432901/30366096-3b7a0d2e-986a-11e7-97c5-b3736d9628e8.png)

In the background page/network tab:

![2017-09-13-1505289471_screenshot](https://user-images.githubusercontent.com/1432901/30366101-3cf1b6a2-986a-11e7-9c5c-61187c5bd79a.png)

New requests appear every few seconds or so. When closing/opening the popup the data is available immediately it seems (or local storage is used).

After a while, there actually is a response:

![2017-09-13-1505289701_screenshot](https://user-images.githubusercontent.com/1432901/30366193-8db33c64-986a-11e7-87ff-99f6bb482535.png)

After login it can also take a while but the path is different: /api/queuecallgroup/.

In fact!! after login the url is HTTP, not HTTPS, the configured endpoint includes most definitely HTTPS.

**Comment by jvanveen** [comment]
Normally these requests will finish in a reasonable time. I added a promise-based timer function, so it won't start another request before the previous one is resolved. Also, the widget data is cleared now on logout and a logout is triggered when the user changes the platform url and saves. A warning was added to notify the user about the autologout.

**Comment by cpoppema** [comment]
It looks like now it won't ever try again when there's a timeout, which is not something we want. It should retry, but only after the timeout has expired.
