### ISSUE TITLE
No autofocus in Firefox

### ISSUE THREAD

**Issue by cpoppema** [VoIPGRID/click-to-dial#83]
### Version

2.1.0

### File / Feature

Autofocus

### Expected behaviour

To focus the first input field when the popup opens.

### Actual behaviour

There is no focus.

<img width="321" alt="autofocus-firefox" src="https://user-images.githubusercontent.com/1432901/31077506-0b286048-a77f-11e7-9b53-f59a207152ae.png">

### Other info

There is currently an open bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1324255

Suggested workaround is 100ms timeout:

```
setTimeout(() => {
  document.querySelector('body').focus();
}, 100);
```

It consistently didn't work on my windows device, it sometimes worked on linux.

**Comment by TomOffringa** [comment]
Jeroen and I both can't reproduce the focus not working anymore. The workaround doesn't work in your case then as well, because we already implemented the abovementioned workaround.

**Comment by cpoppema** [comment]
> It consistently didn't work on my windows device, it sometimes worked on linux.

You also can't reproduce this on windows ?

**Comment by cpoppema** [comment]
For a different plugin that contains the beforementioned workaround, I can consistently reproduce it _not_ working for Firefox on Windows. Sounds like the workaround might not work for Windows.
