### ISSUE TITLE
Dropdown with availability options doesn't have a bottom for Chrome + Windows

### ISSUE THREAD

**Issue by cpoppema** [VoIPGRID/click-to-dial#87]
### Version

2.1.0

### File / Feature

Dropdown with availability options In Chrome on Windows

### Expected behaviour

There should be a visible divider/line/bottom.

### Actual behaviour

![bottom-availability-select](https://user-images.githubusercontent.com/1432901/31077936-a950676a-a780-11e7-8115-54064477ea83.png)

**Comment by jvanveen** [comment]
Fixed in https://github.com/VoIPGRID/click-to-dial/commit/a33dcec8c2fb2900c8120247ab714ad515927b4f
